"""Make price nullable

Revision ID: 181e8d0220fc
Revises: c1fe58f11f5f
Create Date: 2024-07-05 16:16:52.944042

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '181e8d0220fc'
down_revision = 'c1fe58f11f5f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('plants', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               nullable=False)

    # ### end Alembic commands ###
